source:
  type: usgs
  url: https://earthquake.usgs.gov/fdsnws/event/1/query
  poll_interval_seconds: 3600
  min_magnitude: 1.0

kafka:
  bootstrap_servers: kafka:9092
  topic: earthquakes
  weather_topic: weather

storage:
  type: postgresql
  host: postgres
  port: 5432
  database: earthquake_db
  user: postgres
  password: 12345